### ISSUE TITLE
No utils folder

### ISSUE THREAD

**Issue by kulkarni-harsh** [tadaspetra/flutter-projects#1]
I've forked & cloned the repo. In participant_page.dart at line **6** there is 
**import 'package:creatorstudio/utils/app_id.dart';**  which throws error 
**"Target of URI doesn't exist: 'package:creatorstudio/utils/app_id.dart'."**
Correct me if I'm doing something wrong

**Comment by kulkarni-harsh** [comment]
Nvm found the folder is in gitignore

**Comment by tadaspetra** [comment]
Yeah. Might be better to push the utils with an "add app id here" string
